<a href="https://colab.research.google.com/github/Sagar8902/Git/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing numpy

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

## Numpy

In [ ]:
list = [i for i in range(1,21)]
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [ ]:
print(type(list))

<class 'list'>


In [ ]:
%timeit (list**2 for i in list)

221 ns ± 9.18 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
arr = np.array(list)

In [ ]:
%timeit arr**2

580 ns ± 3.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Numpy
- np.array
- np.arange

In [ ]:
list1 = [1,5,65,1,5,7,98,25,65,32,45,36]
np_array = np.array(list1)

In [ ]:
type(np_array)

numpy.ndarray

In [ ]:
np_array.ndim

1

In [ ]:
np_array.shape

(12,)

In [ ]:
np_array2 = np.arange(5,12)

In [ ]:
np_array2

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
np_array3 = np.arange(5,12,2)

In [ ]:
type(np_array2)

numpy.ndarray

### Multi-Dimentional Array

In [ ]:
list_2D = [[1,2,3],
          [4,5,6],
          [7,8,9]]

In [ ]:
list_2D[0]

[1, 2, 3]

In [ ]:
list_2D[1]

[4, 5, 6]

In [ ]:
list_2D[2]

[7, 8, 9]

In [ ]:
#access 5

list_2D[1][1]

5

In [ ]:
# Access 7

list_2D[2][0]

7

In [ ]:
nd_array_2D = np.array(list_2D)

In [ ]:
type(nd_array_2D)

numpy.ndarray

In [ ]:
nd_array_2D.shape

(3, 3)

In [ ]:
nd_array_2D.ndim

2

In [ ]:
%timeit (nd_array_2D**2 for i in nd_array_2D)

230 ns ± 13.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
%timeit (list_2D**2 for i in list_2D)

217 ns ± 10.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
n1 = np.random.randint(1,99)
n1

67

In [ ]:
type(n1)

int

In [ ]:
n2= np.random.randint(1,999,(5,6))
n2

array([[436,  39, 754, 709, 998, 394],
       [ 75, 500, 528, 118, 857, 955],
       [135, 195, 426, 820, 180,  78],
       [326, 201, 158, 265,  54, 666],
       [575, 943, 406,  81, 908, 811]])

In [ ]:
type(n2)

numpy.ndarray

In [ ]:
# Access 820
n2[2][3]

820

In [ ]:
# Access 81
n2[4][3]

81

### Array Slicing

In [ ]:
n2

array([[436,  39, 754, 709, 998, 394],
       [ 75, 500, 528, 118, 857, 955],
       [135, 195, 426, 820, 180,  78],
       [326, 201, 158, 265,  54, 666],
       [575, 943, 406,  81, 908, 811]])

In [ ]:
n2[0]

array([436,  39, 754, 709, 998, 394])

In [ ]:
n2[3]

array([326, 201, 158, 265,  54, 666])

In [ ]:
n2[:,0]

array([436,  75, 135, 326, 575])

In [ ]:
n2[:,5]

array([394, 955,  78, 666, 811])

In [ ]:
#Access 54

n2[3,4]

54

In [ ]:
#Access 811

n2[4,-1]
n2[-1,-1]

811

### Masking

In [ ]:
a1 = np.random.randint(1,50,8)

In [ ]:
a1

array([36, 33, 28, 39, 46, 31, 29, 10])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
mask = (a1 > 30)

In [ ]:
print(mask)
a1[mask]

[ True  True False  True  True  True False False]


array([36, 33, 39, 46, 31])

In [ ]:
a1[a1 > 35] # number ina array > 35

array([36, 39, 46])

In [ ]:
a1

array([36, 33, 28, 39, 46, 31, 29, 10])

In [ ]:
a2 = np.random.randint(1,99,(4,6))

In [ ]:
a2

array([[28, 13, 56, 51, 24, 64],
       [22, 17, 96,  1, 65, 41],
       [18, 13, 32, 79, 64, 22],
       [ 4, 12, 25, 35, 53,  5]])

In [ ]:
a2[a2 > 50] # numbers in array > 50

array([56, 51, 64, 96, 65, 79, 64, 53])

In [ ]:
# > 70 in 3rd row

A1  = a2[2,:] > 70

In [ ]:
a2[2,:][A1]

array([79])

In [ ]:
# > 50 in 2nd row

A2 = a2[:,1] > 15

In [ ]:
a2[:,1][A2]

array([17])

### Operations on Numpy

In [ ]:
L1 = np.random.randint(1,25,8)
L2 = np.random.randint(1,25,8)

In [ ]:
L1

array([22, 10, 21,  9, 13,  4,  8, 16])

In [ ]:
L2

array([ 5, 15, 12, 12, 10, 10,  4, 12])

In [ ]:
L1 + L2

array([27, 25, 33, 21, 23, 14, 12, 28])

In [ ]:
L1 - L2

array([17, -5,  9, -3,  3, -6,  4,  4])

In [ ]:
L1 * L2

array([110, 150, 252, 108, 130,  40,  32, 192])

In [ ]:
L1 / L2

array([4.4       , 0.66666667, 1.75      , 0.75      , 1.3       ,
       0.4       , 2.        , 1.33333333])

In [ ]:
L1 ** L2

array([    5153632, -1530494976,   232284689, -1038305055,   419538377,
           1048576,        4096,           0])

In [ ]:
L1 // L2

array([4, 0, 1, 0, 1, 0, 2, 1])

In [ ]:
L1.dot(L2)

1014

In [ ]:
L1.sum()

103

In [ ]:
L2.sum()

80

In [ ]:
L1.prod()

276756480

In [ ]:
L1.mean()

12.875

In [ ]:
L1.max()

22

In [ ]:
L1_2D = np.random.randint(1,50,(2,3))
L2_2D = np.random.randint(1,50,(2,3))

In [ ]:
L1_2D * L2_2D

array([[1073, 1980,  329],
       [  47, 2009,   50]])

In [ ]:
L1_2D + L2_2D

array([[66, 89, 54],
       [48, 90, 15]])

In [ ]:
L1_2D

array([[29, 45,  7],
       [ 1, 49, 10]])

In [ ]:
L2_2D

array([[37, 44, 47],
       [47, 41,  5]])

In [ ]:
L1_2D -L2_2D

array([[ -8,   1, -40],
       [-46,   8,   5]])

In [ ]:
L1_2D * L2_2D

array([[1073, 1980,  329],
       [  47, 2009,   50]])

In [ ]:
L1_2D = np.random.randint(1,50,(2,3))
L2_2D = np.random.randint(1,50,(5,3))

In [ ]:
L1_2D

array([[40, 16, 10],
       [42, 11, 20]])

In [ ]:
L2_2D

array([[15, 11, 20],
       [18, 11, 25],
       [28, 20,  8],
       [15, 22, 36],
       [ 2,  1, 45]])